### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GitHubUser2069** [SebyPlays/Java-ConsolePrinter-API#1]
Wenn i try to use the API, ther is an Error:

Your System isn't officially supported yet!
Some features might not be available due to an unidentified OS.
 Please report this incident here:
https://github.com/sebyplays/Java-ConsolePrinter-API/issues

So i will report it here!

**Comment by CheeseTastisch** [comment]
Hey

that's because your system is not linux or windows.
The current version of the system only works on Windows and Linux!

**Comment by GitHubUser2069** [comment]
But why it dosn't work for MacOS?

PLEAS MAKE THAT IT WORK

**Comment by SebyPlays** [comment]
I will try my best, ? About to fix it in a few hours :)

**Comment by SebyPlays** [comment]
This issue should be fixed by now.

Please confirm if it works, and I'll close this thread.
